name: SharePoint Sync to Dashboard

on:
  schedule:
    # Roda todos os dias as 03h00 UTC da madrugada (meia noite horario de brasilia)
    - cron: '0 3 * * *'
  
  # Habilita execução manual do GitHub Actions se você quiser
  workflow_dispatch:

jobs:
  sync_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # Faz cache das bibliotecas para baixar mais rápido futuramente
          
      - name: Install Dependencies
        working-directory: ./dashboard-depad/scripts/sharepoint_sync
        run: pip install -r requirements.txt
        
      - name: Run Python Sync Script
        working-directory: ./dashboard-depad/scripts/sharepoint_sync
        env:
          # Variáveis para o SharePoint
          SHAREPOINT_SITE_URL: ${{ secrets.SHAREPOINT_SITE_URL }}
          SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
          
          # Variáveis para o Supabase (Salvar no banco)
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          
        run: python main.py
